#!/bin/sh

if [ -z $1 ]; then
  echo No port specified
  exit 1
fi

PORT=$1

pgrep -f "autossh.*$PORT" > /dev/null
if [ $? != 0 ]; then
  exit 2  # No autossh running for specified port
fi;

for p in $(pstree -p $(pgrep -f "autossh.*$PORT") | grep -oE '[0-9]+'); do
  kill -KILL $p
done;
