#!/bin/sh

MOD_FILES=$(git status --porcelain  | grep -e '^[^\?]' | wc -l)

if [ $MOD_FILES != 0 ]; then
  git stash
fi

git pull -r && git push

if [ $MOD_FILES != 0 ]; then
  git stash apply
  git stash drop
fi
