#!/bin/sh
#
# Turn of the screen after 15 seconds idle, but turn it off upon any activity.
# This script is meant to be run when the system is locked, to keep the screen
# off almost permanently.

swayidle \
  timeout 15 'swaymsg "output * dpms off"' \
  resume 'swaymsg "output * dpms on"'
