#!/bin/sh
#
# Sets random wallpapres from the pool
#
# Wallpapers currently in the pool are split per aspect ratio.
# Directories take names like "3440x1440.UW-QHD".
#
# The script set one at random for each display, making sure the resolution
# matches.

set -e
set -o pipefail
set -x

OUTPUTS=$(swaymsg -t get_outputs | jq -c '.[] | {mode: ((.current_mode.width|tostring) + "x" + (.current_mode.height|tostring)), name: .name}')
BASE_LOCATION=$HOME/pictures/wallpapers/

COMMAND=/usr/bin/swaybg

for OUTPUT in $OUTPUTS; do
  NAME=$(echo $OUTPUT | jq -r '.name')
  MODE=$(echo $OUTPUT | jq -r '.mode')

  # Skip displays that seem to be inactive.
  if [ $MODE != "nullxnull" ]; then
    LOCATION=$BASE_LOCATION/${MODE}*
    FILE=$(/usr/bin/ls -1 $LOCATION | sort -R | tail -n 1)
    WALLPAPER=$LOCATION/$FILE

    COMMAND="$COMMAND -o $NAME -i $WALLPAPER -m fill"
  fi
done

$COMMAND
