#!/usr/bin/env python2

import requests
import json

r = requests.get("http://api.bitcoinaverage.com/no-mtgox/ticker/USD")
j = json.loads(r.text)
value = (j["ask"]+j["bid"])/2

print("${:.2f}".format(value))
