#!/bin/sh

. $HOME/.config/usrc.d/usrc.conf

start_daemon() {
    local _n
    for _n; do
        eval _do=\${${_n}_flags}
        if [ X"${_do}" != X"NO" ]; then
            /bin/sh -c "$HOME/.config/usrc.d/${_n} start ${_bg}"
        fi
    done
}

if [ X$1 == "Xstartup" ]; then
    _bg = "&"
    # Start configured services
    if [ -n "${services}" ]; then
            echo -n 'starting package daemons:'
            for _r in $services; do
                    [ -x $HOME/.config/usrc.d/${_r} ] && start_daemon ${_r}
            done
            echo '.'
    fi
fi
