#!/usr/bin/env python
#
# Reports the local weather for home sweet home.

import json
import os.path
import requests

from datetime import datetime

r = requests.get("https://api.forecast.io/forecast/" +
                 "5ddb40655ee526795f617679b857536a/" +
                 "-34.597378,-58.389587?units=si")
j = json.loads(r.text)

t = os.path.expanduser("~/.cache/weather-{}".format(
                       datetime.now().isoformat()))
f = open(t, "w")
f.write(json.dumps(j, indent=2))
f.close()

print("Current temperature is {} degrees celsius.".format(
      j["currently"]["temperature"]))
print(j["hourly"]["summary"])
print(j["daily"]["summary"])
