#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument and the path of the
# current image as its second argument.
# sxiv(1) blocks until this script terminates. It then checks if the image
# has been modified and reloads it.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

read file
case "$1" in
"C-c")
	echo -n "$file" | xsel -i ;;
"C-e")
	urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & ;;
"C-g")
	gimp "$file" & ;;
"C-comma")
	exec jpegtran -rotate 270 -copy all -outfile "$file" "$file" ;;
"C-period")
	exec jpegtran -rotate  90 -copy all -outfile "$file" "$file" ;;
"C-slash")
	exec jpegtran -rotate 180 -copy all -outfile "$file" "$file" ;;
"C-less")
	exec mogrify -rotate -90 "$file" ;;
"C-greater")
	exec mogrify -rotate +90 "$file" ;;
"C-question")
	exec mogrify -rotate 180 "$file" ;;
"C-d")
        trash "$file" ;;
esac

